{% set name = "arelle-release" %}
{% set version = "2.30.25" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: a444eef4782d08306b36941022411477d9bc0e02ac40dc75d7aefff50d8e8937

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  entry_points:
    - arelleCmdLine = arelle.CntlrCmdLine:main
    - arelleGUI = arelle.CntlrWinMain:main

requirements:
  host:
    - python >=3.8
    - setuptools >=73,<74
    - setuptools-scm >=8.1,<9
    - wheel >=0.44,<0.45
    - pip
  run:
    - python >=3.8
    - certifi
    - filelock
    - isodate ==0.*
    - lxml >=4,<6
    - numpy >=1,<3
    - openpyxl ==3.*
    - pyparsing ==3.*
    - python-dateutil ==2.*
    - regex

test:
  imports:
    - arelle
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://arelle.org
  dev_url: https://github.com/Arelle/Arelle
  doc_url: https://arelle.org/arelle/documentation/
  summary: >
    Arelle is an end-to-end open source XBRL platform, which provides the XBRL community with an easy to use set of tools. It supports XBRL and its extension features in an extensible manner. It does this in a compact yet robust framework that can be used as a desktop application and can be integrated with other applications
    and languages utilizing its web service.
  license: Apache-2.0
  license_file:
    - LICENSE.md

extra:
  recipe-maintainers:
    - zschira
    - zaneselvans
    - aaroncameron-wk
    - allenbross-wf
    - austinmatherne-wk
    - derekgengenbacher-wf
    - hefischer
    - sagesmith-wf
    - stevenbronson-wk
