{% set name = "arelle-release" %}
{% set version = "2.2.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/arelle-release-{{ version }}.tar.gz
  sha256: 576dc956ef157293f4ea14eea898a36d21b31d1d8b35bc731dc4f4cb79080e5a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - setuptools-scm
    - pip
  run:
    - python >=3.7
    - certifi
    - isodate ==0.*
    - lxml ==4.*
    - numpy ==1.*
    - openpyxl ==3.*
    - pyparsing ==3.*
    - regex

test:
  imports:
    - arelle
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/arelle-release/
  summary: An open source XBRL platform.
  license: Apache-2.0
  license_file:
    - LICENSE.md

extra:
  recipe-maintainers:
    - zschira
