{% set name = "arelle-release" %}
{% set version = "2.13.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/arelle-release-{{ version }}.tar.gz
  sha256: 4b2ad635fe9400a889ea068a2710ff5124c644c8d905536ed0515af6a3e3ad2c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  entry_points:
    - arelleCmdLine = arelle.CntlrCmdLine:main
    - arelleGUI = arelle.CntlrWinMain:main

requirements:
  host:
    - python >=3.7
    - setuptools-scm
    - pip
  run:
    - python >=3.7
    - certifi
    - isodate ==0.*
    - lxml ==4.*
    - numpy ==1.*
    - openpyxl ==3.*
    - pyparsing ==3.*
    - regex

test:
  imports:
    - arelle
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://arelle.org
  dev_url: https://github.com/Arelle/Arelle
  doc_url: https://arelle.org/arelle/documentation/
  summary: >
    Arelle is an end-to-end open source XBRL platform, which provides the XBRL community with an easy to use set of tools. It supports XBRL and its extension features in an extensible manner. It does this in a compact yet robust framework that can be used as a desktop application and can be integrated with other applications
    and languages utilizing its web service.
  license: Apache-2.0
  license_file:
    - LICENSE.md

extra:
  recipe-maintainers:
    - zschira
    - zaneselvans
    - aaroncameron-wk
    - allenbross-wf
    - austinmatherne-wk
    - derekgengenbacher-wf
    - hefischer
    - sagesmith-wf
    - stevenbronson-wk
